#!/bin/sh

set -e

fluentd_conf() {
# echo '<source>'
# echo '  @type forward'
# echo '  @label input'
# echo '  port 24224'
# echo '  bind 0.0.0.0'
# echo '  skip_invalid_event true'
# echo '</source>'
# echo ''
# echo '<label @input>'
# echo '  <match docker.**>'
# echo '    @type copy'
# echo '    <store>'
# echo '      @type relabel'
# echo '      @label @output_file'
# echo '    </store>'
# echo ''
# echo '    <store>'
# echo '      @type relabel'
# echo '      @label @log_analysis'
# echo '    </store>'
# echo '  </match>'
# echo '</label>'
# echo ''
# echo '<label @output_file>'
# echo '  @type file_alternative'
# echo '  path /var/log/shizai/fluentd/docker.%Y%m%d.log'
# echo '  symlink_path /var/log/shizai/fluentd/docker_current'
# echo '  buffer_type file'
# echo '  buffer_path /var/log/shizai/fluentd/buffer/'
# echo '</label>'
# echo ''
# echo '<label @log_analysis>'
# echo '  <filter docker.shizai.**>'
# echo '    @type parser'
# echo '    format  /^(?<time>[^ ]* [^ ]*) *(?<loglevel>\[.*\]) (?<message>.*)/'
# echo '    time_format %Y-%m-%d %H:%M:%S'
# echo '    key_name log'
# echo '    emit_invalid_record_to_error false'
# echo '  </filter>'
# echo ''
# echo '  <match docker.shizai.**>'
# echo '    @type rewrite_tag_filter'
# echo '    <rule>'
# echo '      key       level'
# echo '      pattern   /^\[WARNING.*\]/'
# echo '      tag       docker.log.alert'
# echo '    </rule>'
# echo '  </match>'
# echo '  <match docker.shizai.**>'
# echo '    @type rewrite_tag_filter'
# echo '    <rule>'
# echo '      key       level'
# echo '      pattern   /^\[ERROR.*\]/'
# echo '      tag       docker.log.escalation'
# echo '    </rule>'
# echo '  </match>'
# echo ''
# echo '  <match docker.log.alert>'
# echo '    @type copy'
# echo '    <store>'
# echo '      @type file_alternative'
# echo '      path /var/log/shizai/fluentd/docker.alert.%Y%m%d.log'
# echo '      symlink_path /var/log/shizai/fluentd/docker_alert_current'
# echo '      buffer_type file'
# echo '      buffer_path /var/log/shizai/fluentd/buffer/'
# echo '    </store>'
# echo ''
# echo '    <store>'
# echo '      @type relabel'
# echo '      @label @alert_log_analysis'
# echo '    </store>'
# echo '  </match>'
# echo '  <match docker.log.escalation>'
# echo '    @type copy'
# echo '    <store>'
# echo '      @type file_alternative'
# echo '      path /var/log/shizai/fluentd/docker.escalation.%Y%m%d.log'
# echo '      symlink_path /var/log/shizai/fluentd/docker_escalation_current'
# echo '      buffer_type file'
# echo '      buffer_path /var/log/shizai/fluentd/buffer/'
# echo '    </store>'
# echo ''
# echo '    <store>'
# echo '      @type relabel'
# echo '      @label @escalation_log_analysis'
# echo '    </store>'
# echo '  </match>'
# echo '</label>'
}

fluentd_conf > /fluentd/etc/fluent.conf
