Vagrant.configure("2") do |config|
  def define_machine_name(c, name)
    c.vm.provider :virtualbox do |vbox|
      vbox.name = name
    end
  end

  now_path = Dir.pwd
  current_path = now_path.gsub(/\/vagrantfile/, '')
  config.vm.box = "bento/centos-7.8"
  config.vm.hostname = "shizai.local"
  config.vm.network "private_network", ip: "192.168.33.77"
  config.vm.synced_folder current_path, "/var/vagrantshare"
  config.vm.provision "shell", path: "./provisioning.sh"
  config.vm.provider "virtualbox" do |vb|
    # vb.memory = "4096"
    # vb.memory = "2048"
    vb.memory = "1024"
  end
end
